### ISSUE TITLE
sentry/raven configuration

### ISSUE THREAD

**Issue by atherdon** [roshan2008web/loopback_tutorial#2]
`Raven.config('https://77aa2ee9a7ce484497f56278982a0809@sentry.io/305339').install()`

Init:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L17

How to use this tracer:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L60

if you'll cover your code well with this tracer - when you'll break something - I'll receive an email notification and will be able to understand more clearly what was goes wrong.

![image](https://user-images.githubusercontent.com/1469198/37542679-b443d8f0-2967-11e8-8d98-7fc3e9aabe6b.png)

**Comment by roshan2008web** [comment]
1. raven has been installed
2. Initialized in server/server.js
3. covered some code with the tracer in server/server.js
