### ISSUE TITLE
git

### ISSUE THREAD

**Issue by atherdon** [roshan2008web/loopback_tutorial#6]
# Description/Steps to reproduce

- [ ] convert our flow to good git-flow.
- [ ] broke few forks(0)
- [ ] make 30 commits (0)
- [ ] make 9 pull requests (0)
- [ ] make 6 merge conflicts and fix them (0)
- [ ] make 5-10 future branches, related in a different ways(few times checkout from develop, few times from each other feature branch)(0)
- [ ] 6 branch merges(0)

**use command line only**

https://github.com/blog/831-issues-2-0-the-next-generation
https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message
https://guides.github.com/features/issues/

https://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github

# Expected result

# Additional information

**Comment by atherdon** [comment]
@roshan2008web give me write access, so i can assign tasks to you

**Comment by roshan-auto** [comment]
@atherdon I've added you as a collaborator. does it give you write access or is there a different way of giving the write access?

**Comment by atherdon** [comment]
main goal is to have ability to assign tasks to you. still cannot do this.


On 04-Jun-2018 at 08:24 AM, roshan2008web wrote:


@atherdon <https://github.com/atherdon> I've added you as a collaborator.
does it give you write access or is there a different way of giving the
write access?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/roshan2008web/loopback_tutorial/issues/6#issuecomment-394273771>,
or mute the thread
